### ISSUE TITLE
Add support for Dataloaders

### ISSUE THREAD

**Issue by olivierlemasle** [excitement-engineer/ktor-graphql#17]
Support for dataloaders (_batching_) would be very useful to solve the N+1 problem.

https://www.graphql-java.com/documentation/v14/batching/

**Comment by excitement-engineer** [comment]
I have updated the library so that dataloaders can be used in conjunction with this project. I have created release 2.0.0 with support for this. I pushed the code to the master branch already and it should be available in your project if you bump your dependency version. I will create release notes in the next few days. 

For docs on how to use dataloaders see [Guide](https://github.com/excitement-engineer/ktor-graphql#guides)
